# -*- coding: utf-8 -*-
"""tumor_feature_extraction_VGG19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p_9YzsqrJZQkT6Jh-hM_ctbxgrfIPF2L
"""

!pip install tensorflow keras matplotlib seaborn graphviz scikit-learn

import os
import cv2
import gzip
import pickle
import numpy as np
import pandas as pd
import tensorflow as tf
from time import time
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Define the path to the image folder
image_folder = "/content/drive/MyDrive/DcbData/png_expanded_tumor_middle_10"

# Load clinical and demographic data from the Excel file
clinical_data_path = '/content/drive/MyDrive/DcbData/Clinical_and_Other_Features.xlsx'


clinical_data = pd.read_excel(clinical_data_path)

# Extract relevant columns and rename for consistency
clinical_data = clinical_data[['Patient ID', 'Pathologic Response to Neoadjuvant Therapy'] + [col for col in clinical_data.columns if col.startswith('Breast_MRI_')]]
clinical_data.columns = [col.replace(' ', '_') for col in clinical_data.columns]
clinical_data = clinical_data.rename(columns={'Patient_ID': 'patient_id', 'Pathologic_Response_to_Neoadjuvant_Therapy': 'response'})

# Convert 'Breast_MRI_001' to '001' in the patient_id column
clinical_data['patient_id'] = clinical_data['patient_id'].apply(lambda x: x.split('_')[-1])

# Convert response to binary: 1 means response, anything other than 1 means no response
clinical_data['response'] = clinical_data['response'].apply(lambda x: 1 if x == 1 else 0)

# Create a dictionary to map patient_id to response
clinical_dict = dict(zip(clinical_data['patient_id'], clinical_data['response']))

# Function to load images
def load_images(image_folder):
    images = {}
    for filename in os.listdir(image_folder):
        if filename.endswith('.png'):
            image_name = filename[:-4]  # Remove the '.png' part
            image_path = os.path.join(image_folder, filename)
            image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
            if image is not None:
                images[image_name] = image
            else:
                print(f"Warning: {filename} could not be read.")
    return images

# Load images
image_data = load_images(image_folder)

image_data

# Map images to their class labels and count the number per class
class_images = {0: [], 1: []}
for filename in image_data.keys():
    patient_id = filename.split('-')[0]
    class_label = clinical_dict.get(patient_id)
    if class_label is not None:
        class_images[class_label].append(filename)
    else:
        print(f"Patient ID {patient_id} not found in clinical data.")

num_class_0 = len(class_images[0])
num_class_1 = len(class_images[1])

# Determine majority and minority classes
if num_class_0 > num_class_1:
    majority_class = 0
    minority_class = 1
    num_major = num_class_0
    num_minor = num_class_1
else:
    majority_class = 1
    minority_class = 0
    num_major = num_class_1
    num_minor = num_class_0

# Calculate the number of augmentations needed per image in the minority class
n_aug_major = 1  # Total images per original image in majority class (including original)
n_aug_minor = int(np.ceil((num_major * n_aug_major) / num_minor))

# Load pre-trained VGG16 model
base_model = tf.keras.applications.VGG19(
    weights='imagenet', include_top=False, input_shape=(224, 224, 3)
)
model = tf.keras.models.Model(
    inputs=base_model.input, outputs=base_model.get_layer('block5_pool').output
)

#Function: Preprocess and Extract
def preprocess_image(image):
    image = cv2.resize(image, (224, 224))
    image = np.stack((image,)*3, axis=-1)  # Convert grayscale to RGB
    image = tf.keras.applications.vgg19.preprocess_input(image)
    return np.expand_dims(image, axis=0)

# Function: Augment image
def augment_image(image, n_aug):
    augmented_images = []
    # Original image
    augmented_images.append(image)
    rows, cols = image.shape

    for i in range(n_aug):
        transformed_image = image.copy()

        # Random translation
        tx = np.random.uniform(-0.1, 0.1) * cols
        ty = np.random.uniform(-0.1, 0.1) * rows
        M_translation = np.float32([[1, 0, tx], [0, 1, ty]])
        transformed_image = cv2.warpAffine(transformed_image, M_translation, (cols, rows))

        # Random rotation
        angle = np.random.uniform(-15, 15)
        M_rotation = cv2.getRotationMatrix2D((cols / 2, rows / 2), angle, 1)
        transformed_image = cv2.warpAffine(transformed_image, M_rotation, (cols, rows))

        # Random scaling
        scale = np.random.uniform(0.9, 1.1)
        M_scale = cv2.getRotationMatrix2D((cols / 2, rows / 2), 0, scale)
        transformed_image = cv2.warpAffine(transformed_image, M_scale, (cols, rows))

        # Random shearing
        shear_factor = np.random.uniform(-0.1, 0.1)
        M_shear = np.float32([[1, shear_factor, 0], [shear_factor, 1, 0]])
        transformed_image = cv2.warpAffine(transformed_image, M_shear, (cols, rows))

        augmented_images.append(transformed_image)

    return augmented_images


# Function: Extract features
def extract_features(image_data):
    features = {}
    for filename, image in image_data.items():
        # Get patient id
        patient_id = filename.split('-')[0]
        class_label = clinical_dict.get(patient_id)
        if class_label is None:
            print(f"Patient ID {patient_id} not found in clinical data.")
            continue

        # Determine n_aug based on class_label
        if class_label == majority_class:
            n_aug = n_aug_major - 1  # Since augment_image includes the original image
        else:
            n_aug = n_aug_minor - 1

        # Ensure n_aug is at least 0
        n_aug = max(n_aug, 0)

        # Get augmented images
        augmented_images = augment_image(image, n_aug)

        for idx, aug_image in enumerate(augmented_images):
            preprocessed_image = preprocess_image(aug_image)
            feature = model.predict(preprocessed_image, verbose=0).flatten()
            # Create a unique key for each augmented image
            feature_key = f"{filename}_{idx}"
            features[feature_key] = feature
    return features

# Measure execution time for feature extraction
start_time = time()
features_extracted = extract_features(image_data)
end_time = time()
extraction_time_taken = end_time - start_time
print(f"Time taken for feature extraction: {extraction_time_taken:.4f} seconds")

features_extracted

# Save the features to a compressed file
features_path = '/content/drive/MyDrive/DcbData/features_extracted_VGG19_tumor_mid10_5_augmented_bal_1.pkl.gz'
with gzip.open(features_path, 'wb') as f:
    pickle.dump(features_extracted, f, protocol=pickle.HIGHEST_PROTOCOL)
print(f"Saved compressed features to {features_path}.")